---
# Self-signed ClusterIssuer for testing
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# Certificate for docs.local (managed by cert-manager)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docs-cert
  namespace: default
spec:
  secretName: docs-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - cert-observer
  commonName: docs.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - docs.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# Certificate for admin.local (managed by cert-manager)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-cert
  namespace: default
spec:
  secretName: admin-tls
  duration: 1440h # 60 days
  renewBefore: 240h # 10 days
  subject:
    organizations:
      - cert-observer
  commonName: admin.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - admin.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# Ingress using cert-manager managed certificate
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs
  namespace: default
spec:
  tls:
  - hosts:
    - docs.local
    secretName: docs-tls
  rules:
  - host: docs.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-server
            port:
              number: 8080
---
# Ingress using cert-manager managed certificate
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin
  namespace: default
spec:
  tls:
  - hosts:
    - admin.local
    secretName: admin-tls
  rules:
  - host: admin.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-server
            port:
              number: 8080
